a) in graphics.c commented-out lines 1836-1837    which caused \begin{equation}...\end{equation}    to be output to l2r_nnnn.tex as $$...$$ b) in latex2png script, changed order in which to try conversion    from latex-dvi / pdflatex / xelatex    to   pdflatex  / xelatex  / latex
git-svn-id: https://svn.code.sf.net/p/latex2rtf/code/trunk@1236 bedafb05-6a7b-466a-8c5e-1828fe372967

diff --git a/scripts/latex2png b/scripts/latex2png
--- a/scripts/latex2png
+++ b/scripts/latex2png
@@ -32,8 +32,8 @@ SED="sed"
 # !!!!!!!!!!!!!!!! Note !!!!!!!!!!!!!!
 # Under MS Windows, although this script runs under bash shell,
 # LaTeX is run in the Windows environment and thus needs the ";" as separator.
-TEXINPSEP=":" #Unix
-#TEXINPSEP=";"  #MS Windows
+#TEXINPSEP=":" #Unix
+TEXINPSEP=";"  #MS Windows
 VERSION="1.40"
 
 help()
@@ -78,7 +78,6 @@ home_dir="."    # default to current directory
 ext="tex"       # default to latex input
 out="-depth 24" # default to color output
 inline=0        # default to no special equation processing
-tikz=0          # default to not processing a tikzpicture
 
 while [ -n "$1" ]; do
 case $1 in
@@ -132,15 +131,24 @@ if [ $ext = "tex" ] ; then
 
     inline=`${GREP} -c INLINE_DOT_ON_BASELINE $name.$ext`
 
-    tikz=`${GREP} -c tikzpicture $name.$ext`
-
     rm -f $name.dvi
     rm -f $name.pdf
     rm -f $name.eps
     rm -f $name.png
 
-    if [ $tikz -gt 1 ] ; then
-       $PDFLATEX $name > /dev/null
+
+    $PDFLATEX $name > /dev/null
+    if [ -e "$name.pdf" ] ; then
+       $PDF2EPS $name.pdf $name.eps
+       if [ ! -e "$name.eps" ] ; then
+          echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
+          exit 1
+       fi
+    else
+       if [ $opt_k -eq 1 ] ; then
+          echo "latex2png: pdflatex failed to translate $name.tex to $name.pdf, trying xelatex"
+       fi
+       $XELATEX $name > /dev/null
        if [ -e "$name.pdf" ] ; then
           $PDF2EPS $name.pdf $name.eps
           if [ ! -e "$name.eps" ] ; then
@@ -149,56 +157,21 @@ if [ $ext = "tex" ] ; then
           fi
        else
           if [ $opt_k -eq 1 ] ; then
-             echo "latex2png: pdflatex failed to translate $name.tex to $name.pdf, trying xelatex"
+             echo "latex2png: xelatex failed to translate $name.tex to $name.dvi, trying latex"
           fi
-          $XELATEX $name > /dev/null
-          if [ -e "$name.pdf" ] ; then
-             $PDF2EPS $name.pdf $name.eps
+          $LATEX $name > /dev/null
+          if [ -e "$name.dvi" ] ; then
+             $DVIPS -o $name.eps $name.dvi
              if [ ! -e "$name.eps" ] ; then
-                echo "latex2png: error: $PDF2EPS failed to translate $name.pdf to $name.eps"
-                exit 1
+               if [ $opt_k -eq 1 ] ; then
+                  echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
+                  exit 1
+               fi
+               exit 1
              fi
           else
-             echo "latex2png: error: $XELATEX failed to translate $name.tex to $name.pdf"
+             echo "latex2png: error: pdflatex, xelatex and latex all failed to translate $name.tex"
              exit 1
-          fi
-       fi
-    else
-       $LATEX $name > /dev/null
-       if [ -e "$name.dvi" ] ; then
-          $DVIPS -o $name.eps $name.dvi
-          if [ ! -e "$name.eps" ] ; then
-            if [ $opt_k -eq 1 ] ; then
-               echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
-            fi
-            exit 1
-          fi
-       else
-          if [ $opt_k -eq 1 ] ; then
-             echo "latex2png: latex failed to translate $name.tex to $name.dvi, trying pdflatex"
-          fi
-          $PDFLATEX $name > /dev/null
-          if [ -e "$name.pdf" ] ; then
-             $PDF2EPS $name.pdf $name.eps
-             if [ ! -e "$name.eps" ] ; then
-                echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
-                exit 1
-             fi
-          else
-             if [ $opt_k -eq 1 ] ; then
-                echo "latex2png: pdflatex failed to translate $name.tex to $name.pdf, trying xelatex"
-             fi
-             $XELATEX $name > /dev/null
-             if [ -e "$name.pdf" ] ; then
-                $PDF2EPS $name.pdf $name.eps
-                if [ ! -e "$name.eps" ] ; then
-                   echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
-                   exit 1
-                fi
-             else
-                echo "latex2png: error: xelatex failed to translate $name.tex to $name.pdf"
-                exit 1
-             fi
           fi
        fi
     fi
@@ -216,25 +189,29 @@ if [ $ext = "tex" ] ; then
            rm -f $name.pdf
            rm $name.eps
            mv $name.tmp $name.tex
-           $LATEX $name > /dev/null
-           if [ -e "$name.dvi" ] ; then
-              $DVIPS -o $name.eps $name.dvi
+
+           $PDFLATEX $name > /dev/null
+           if [ -e "$name.pdf" ] ; then
+              $PDF2EPS $name.pdf $name.eps
            else
               if [ $opt_k -eq 1 ] ; then
-                 echo "latex2png: latex failed to translate $name.tex w/o adj to $name.dvi, trying pdflatex"
+                 echo "latex2png: pdflatex failed to translate $name.tex w/o adj to $name.pdf, trying xelatex"
               fi
-              $PDFLATEX $name > /dev/null
-              if [ ! -e "$name.pdf" ] ; then
+              $XELATEX $name > /dev/null
+              if [ -e "$name.pdf" ] ; then
+                 $PDF2EPS $name.pdf $name.eps
+              else
                  if [ $opt_k -eq 1 ] ; then
-                    echo "latex2png: pdflatex failed to translate $name.tex w/o adj to $name.pdf, trying xelatex"
+                    echo "latex2png: error: xelatex failed to translate $name.tex w/o adj to $name.pdf, trying latex"
                  fi
-                 $XELATEX $name > /dev/null
-                 if [ ! -e "$name.pdf" ] ; then
-                    echo "latex2png: error: xelatex failed to translate $name.tex w/o adj to $name.pdf"
+                 $LATEX $name > /dev/null
+                 if [ -e "$name.dvi" ] ; then
+                    $DVIPS -o $name.eps $name.dvi
+                 else
+                    echo "latex2png: pdflatex, xelatex and latex all failed to translate $name.tex w/o adj"
                     exit 1
                  fi
               fi
-              $PDF2EPS $name.pdf $name.eps
            fi
            if [ ! -e "$name.eps" ] ; then
               echo "latex2png: error: failed to translate $name.tex to $name.eps"
@@ -258,11 +235,10 @@ if [ $ext = "tex" ] ; then
            fi
         fi
         if [ $opt_k -eq 0 ] ; then
-            rm -f $name.dvi $name.aux $name.log $name.out
+            rm -f $name.pdf $name.dvi $name.aux $name.log $name.out
         fi
         exit 0
     fi
-    
 fi
 
 # WH: added "-type TrueColor" to ensure compatibility with older versions of Word and with IrfanView
