updated latex2png to work with tikzpictures.
git-svn-id: https://svn.code.sf.net/p/latex2rtf/code/trunk@1226 bedafb05-6a7b-466a-8c5e-1828fe372967

diff --git a/scripts/latex2png b/scripts/latex2png
--- a/scripts/latex2png
+++ b/scripts/latex2png
@@ -17,7 +17,7 @@
 # (portable gray map) file that can be used to determine the 
 # height of the equation baseline
 #
-#set -x  # uncomment for debugging
+set -x  # uncomment for debugging
 #
 
 DVIPS="dvips -q -l 1 -E -R"
@@ -34,7 +34,7 @@ SED="sed"
 # LaTeX is run in the Windows environment and thus needs the ";" as separator.
 TEXINPSEP=":" #Unix
 #TEXINPSEP=";"  #MS Windows
-VERSION="1.30"
+VERSION="1.10"
 
 help()
 {
@@ -78,6 +78,7 @@ home_dir="."    # default to current directory
 ext="tex"       # default to latex input
 out="-depth 24" # default to color output
 inline=0        # default to no special equation processing
+tikz=0          # default to not processing a tikzpicture
 
 while [ -n "$1" ]; do
 case $1 in
@@ -130,26 +131,31 @@ fi
 if [ $ext = "tex" ] ; then
 
     inline=`${GREP} -c INLINE_DOT_ON_BASELINE $name.$ext`
-
-    rm -f $name.dvi
-    rm -f $name.pdf
-    rm -f $name.eps
-    rm -f $name.png
+    tikz=`${GREP} -c tikzpicture $name.$ext`
 
     $LATEX $name > /dev/null
     
-    if [ -e "$name.dvi" ] ; then
+    if [ $tikz -eq 2 ] ; then
+       $XELATEX $name > /dev/null
+       if [ -e "$name.pdf" ] ; then
+          $PDF2EPS $name.pdf $name.eps
+          if [ ! -e "$name.eps" ] ; then
+             echo "latex2png: error: $PDF2EPS failed to translate $name.pdf to $name.eps"
+             exit 1
+          fi
+       else
+          echo "latex2png: error: $XELATEX failed to translate $name.tex to $name.pdf"
+          exit 1
+       fi
+    
+    elif [ -e "$name.dvi" ] ; then
        $DVIPS -o $name.eps $name.dvi
        if [ ! -e "$name.eps" ] ; then
-         if [ $opt_k -eq 1 ] ; then
-            echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
-         fi
+         echo "latex2png: error: dvips failed to translate $name.dvi to $name.eps"
          exit 1
        fi
     else
-       if [ $opt_k -eq 1 ] ; then
-          echo "latex2png: latex failed to translate $name.tex to $name.dvi, trying pdflatex"
-       fi
+       echo "latex2png: latex failed to translate $name.tex to $name.dvi, trying pdflatex"
        $PDFLATEX $name > /dev/null
        if [ -e "$name.pdf" ] ; then
           $PDF2EPS $name.pdf $name.eps
@@ -158,20 +164,8 @@ if [ $ext = "tex" ] ; then
              exit 1
           fi
        else
-          if [ $opt_k -eq 1 ] ; then
-             echo "latex2png: pdflatex failed to translate $name.tex to $name.pdf, trying xelatex"
-          fi
-          $XELATEX $name > /dev/null
-          if [ -e "$name.pdf" ] ; then
-             $PDF2EPS $name.pdf $name.eps
-             if [ ! -e "$name.eps" ] ; then
-                echo "latex2png: error: eps2eps failed to translate $name.pdf to $name.eps"
-                exit 1
-             fi
-          else
-             echo "latex2png: error: xelatex failed to translate $name.tex to $name.pdf"
-             exit 1
-          fi
+          echo "latex2png: error: latex failed to translate $name.tex to $name.pdf"
+          exit 1
        fi
     fi
  
@@ -185,34 +179,9 @@ if [ $ext = "tex" ] ; then
            # now create an eps without the adjustment stuff
            $SED -e "s/\^I_g//" $name.tex >$name.tmp
            rm $name.tex
-           rm -f $name.pdf
-           rm $name.eps
            mv $name.tmp $name.tex
            $LATEX $name > /dev/null
-           if [ -e "$name.dvi" ] ; then
-              $DVIPS -o $name.eps $name.dvi
-           else
-              if [ $opt_k -eq 1 ] ; then
-                 echo "latex2png: latex failed to translate $name.tex w/o adj to $name.dvi, trying pdflatex"
-              fi
-              $PDFLATEX $name > /dev/null
-              if [ ! -e "$name.pdf" ] ; then
-                 if [ $opt_k -eq 1 ] ; then
-                    echo "latex2png: pdflatex failed to translate $name.tex w/o adj to $name.pdf, trying xelatex"
-                 fi
-                 $XELATEX $name > /dev/null
-                 if [ ! -e "$name.pdf" ] ; then
-                    echo "latex2png: error: xelatex failed to translate $name.tex w/o adj to $name.pdf"
-                    exit 1
-                 fi
-              fi
-              $PDF2EPS $name.pdf $name.eps
-           fi
-           if [ ! -e "$name.eps" ] ; then
-              echo "latex2png: error: failed to translate $name.tex to $name.eps"
-              exit 1
-           fi
-
+           $DVIPS -o $name.eps $name.dvi
            # extract the BoundingBox of the eps without adjustment stuff
            bbb=`${GREP} -C 0 %%BoundingBox: $name.eps`
            llyfin=$(echo $bbb | $AWK -F" " '{print $3}' )
@@ -230,7 +199,7 @@ if [ $ext = "tex" ] ; then
            fi
         fi
         if [ $opt_k -eq 0 ] ; then
-            rm -f $name.dvi $name.aux $name.log $name.out
+            rm -f $name.dvi $name.aux $name.log
         fi
         exit 0
     fi
