Resolve encoding, EOL and tab to space

diff --git a/scripts/latex2png_1 b/scripts/latex2png_1
--- a/scripts/latex2png_1
+++ b/scripts/latex2png_1
@@ -2,7 +2,7 @@
 # Part of latex2rtf by Scott Prahl (Nov 2002)
 #
 # This version uses latex and dvips
-#			   with ps2ps (part of Ghostscript)
+#              with ps2ps (part of Ghostscript)
 #              with convert (Part of ImageMagick)
 #
 # This script file will convert a latex file into a PNG image.
@@ -44,13 +44,13 @@ OPTIONS:
          -d density     (default 144 dpi)
          -o offset      = density/72+2
          -h help        (default '.')
-         -H /home/dir	directory to be included in search path
-         -k         	keep intermediate files (for debugging)
+         -H /home/dir   directory to be included in search path
+         -k             keep intermediate files (for debugging)
 
 EXAMPLE: 
-		 latex2png -d 144 /tmp/file   #create /tmp/file.png at 144 dpi
-		 latex2png file.eps           #create file.png
-		 latex2png file.tex           #create file.png via latex
+         latex2png -d 144 /tmp/file   #create /tmp/file.png at 144 dpi
+         latex2png file.eps           #create file.png
+         latex2png file.tex           #create file.png via latex
          latex2png -H . /tmp/file     #search the cwd for image files
 
 HELP
@@ -63,13 +63,13 @@ echo "latex2png $VERSION"
 exit 0
 }
 
-opt_d=144		# default to 144 dpi
-opt_o=4			# default for 144 dpi
-opt_k=0			# default to killing intermediate files
-home_dir="."	# default to current directory
-ext="tex"		# default to latex input
-out="-depth 24"	# default to color output
-inline=0		# default to no special equation processing
+opt_d=144       # default to 144 dpi
+opt_o=4         # default for 144 dpi
+opt_k=0         # default to killing intermediate files
+home_dir="."    # default to current directory
+ext="tex"       # default to latex input
+out="-depth 24" # default to color output
+inline=0        # default to no special equation processing
 
 while [ -n "$1" ]; do
 case $1 in
@@ -90,13 +90,13 @@ done
 
 # is there an input file?
 if [ -z "$1" ] ; then
-	error "no input file specified"
-	exit 1
+    error "no input file specified"
+    exit 1
 fi
 
 # is it an eps file?
 if [ `echo $1 | ${GREP} -c eps$` -eq 1 ] ; then
-	ext="eps"
+    ext="eps"
 fi
 
 #process 'latex2png file.tex' and 'latex2png file' equivalently
@@ -108,7 +108,7 @@ cd $home_dir
 TEXINPUTS=`pwd`${TEXINPSEP}
 export TEXINPUTS
 cd $dir
-	
+    
 # does the input file exist?
 if [ ! -f "$name.$ext" ] ; then
  echo "error: input file $name.$ext does not exist in directory $dir"
@@ -117,35 +117,35 @@ fi
 
 if [ $ext = "tex" ] ; then
 
-	inline=`${GREP} -c INLINE_DOT_ON_BASELINE $name.$ext`
+    inline=`${GREP} -c INLINE_DOT_ON_BASELINE $name.$ext`
 
-	$LATEX $name > /dev/null
-	
-	if [ ! -e "$name.dvi" ] ; then
-		echo "error: latex failed to translate $name.tex to $name.dvi"
-		exit 1
-	fi
-	
-	$DVIPS -o $name.tmp.eps $name.dvi
-	
-	if [ ! -e "$name.tmp.eps" ] ; then
-		echo "error: dvips failed to translate $name.dvi to $name.tmp.eps"
-		exit 1
-	fi
-	
-	#helps convert work with eps figures
-	$EPS2EPS $name.tmp.eps $name.eps
-	if [ ! -e "$name.eps" ] ; then
-		echo "error: eps2eps (Ghostscript) failed to translate $name.tmp.eps from $name.eps"
-		exit 1
-	fi
+    $LATEX $name > /dev/null
+    
+    if [ ! -e "$name.dvi" ] ; then
+        echo "error: latex failed to translate $name.tex to $name.dvi"
+        exit 1
+    fi
+    
+    $DVIPS -o $name.tmp.eps $name.dvi
+    
+    if [ ! -e "$name.tmp.eps" ] ; then
+        echo "error: dvips failed to translate $name.dvi to $name.tmp.eps"
+        exit 1
+    fi
+    
+    #helps convert work with eps figures
+    $EPS2EPS $name.tmp.eps $name.eps
+    if [ ! -e "$name.eps" ] ; then
+        echo "error: eps2eps (Ghostscript) failed to translate $name.tmp.eps from $name.eps"
+        exit 1
+    fi
 fi
 
 $CONVERT -crop 0x0 $out -density ${opt_d}x${opt_d} $name.eps $name.png
 
 if [ ! -e "$name.png" ] ; then
- 	echo "error: convert (ImageMagick) failed to translate $name.eps from $name.png"
- 	exit 1
+     echo "error: convert (ImageMagick) failed to translate $name.eps from $name.png"
+     exit 1
 fi
 
 # -i is for images of equations that include an extra dot on the baseline
@@ -155,25 +155,25 @@ fi
 #    in $name.tmp.png is removed to create the final image $name.png
 # 
 if [ $inline -eq 1 ] ; then
-	rm -f $name.ppm $name.pbm
+    rm -f $name.ppm $name.pbm
 
-	pngtopnm $name.png > $name.ppm
-	
-	pnmcut -width 1 $name.ppm | ppmtopgm | pgmtopbm > $name.pbm
+    pngtopnm $name.png > $name.ppm
+    
+    pnmcut -width 1 $name.ppm | ppmtopgm | pgmtopbm > $name.pbm
 
-#	offset=`expr ${opt_d} / 72 + 2`
-	pnmcut -left $opt_o $name.ppm | pnmcrop -left | pnmtopng > $name.png 2> /dev/null
+#    offset=`expr ${opt_d} / 72 + 2`
+    pnmcut -left $opt_o $name.ppm | pnmcrop -left | pnmtopng > $name.png 2> /dev/null
 
-	if [ $opt_k -eq 0 ] ; then
-		rm -f $name.ppm
-	fi
+    if [ $opt_k -eq 0 ] ; then
+        rm -f $name.ppm
+    fi
 fi
 
 if [ $opt_k -eq 0 ] ; then
-	rm -f $name.dvi $name.aux $name.log $name.tmp.eps
-	if [ $ext = "tex" ] ; then
-		rm -f $name.eps
-	fi
+    rm -f $name.dvi $name.aux $name.log $name.tmp.eps
+    if [ $ext = "tex" ] ; then
+        rm -f $name.eps
+    fi
 fi
 
 exit 0
diff --git a/scripts/latex2png_2 b/scripts/latex2png_2
--- a/scripts/latex2png_2
+++ b/scripts/latex2png_2
@@ -48,13 +48,13 @@ OPTIONS:
          -d density     (default 144 dpi)
          -o offset      = density/72+2
          -h help        (default '.')
-         -H /home/dir	directory to be included in search path
-         -k         	keep intermediate files (for debugging)
+         -H /home/dir   directory to be included in search path
+         -k             keep intermediate files (for debugging)
 
 EXAMPLE: 
-		 latex2png -d 144 /tmp/file   #create /tmp/file.png at 144 dpi
-		 latex2png file.eps           #create file.png
-		 latex2png file.tex           #create file.png via latex
+         latex2png -d 144 /tmp/file   #create /tmp/file.png at 144 dpi
+         latex2png file.eps           #create file.png
+         latex2png file.tex           #create file.png via latex
          latex2png -H . /tmp/file     #search the cwd for image files
 
 HELP
@@ -67,13 +67,13 @@ echo "latex2png $VERSION"
 exit 0
 }
 
-opt_d=144		# default to 144 dpi
-opt_o=4			# default for 144 dpi
-opt_k=0			# default to killing intermediate files
-home_dir="."	# default to current directory
-ext="tex"		# default to latex input
-out="ppm"		# default to color output
-inline=0		# default to no special equation processing
+opt_d=144       # default to 144 dpi
+opt_o=4         # default for 144 dpi
+opt_k=0         # default to killing intermediate files
+home_dir="."    # default to current directory
+ext="tex"       # default to latex input
+out="ppm"       # default to color output
+inline=0        # default to no special equation processing
 
 while [ -n "$1" ]; do
 case $1 in
@@ -100,7 +100,7 @@ fi
 
 # is it an eps file?
 if [ `echo $1 | ${GREP} -c eps$` -eq 1 ] ; then
-	ext="eps"
+    ext="eps"
 fi
 
 #process 'latex2png file.tex' and 'latex2png file' equivalently
@@ -115,36 +115,36 @@ cd $dir
 
 # does the input file exist?
 if [ ! -f "$name.$ext" ] ; then
-	echo "error: input file $name.$ext does not exist"
-	exit 1
+    echo "error: input file $name.$ext does not exist"
+    exit 1
 fi
 
 rm -f $name.png
 
 if [ $ext = "tex" ] ; then
 
-	inline=`${GREP} -c INLINE_DOT_ON_BASELINE $name.$ext`
+    inline=`${GREP} -c INLINE_DOT_ON_BASELINE $name.$ext`
 
-	$LATEX $name > /dev/null
-	
-	if [ ! -e "$name.dvi" ] ; then
-		echo "error: latex failed to translate $name.tex to $name.dvi"
-		exit 1
-	fi
-	
-	$DVIPS -o $name.eps $name.dvi
-	
-	if [ ! -e "$name.eps" ] ; then
-		echo "error: dvips failed to translate $name.dvi to $name.eps"
-		exit 1
-	fi
+    $LATEX $name > /dev/null
+
+    if [ ! -e "$name.dvi" ] ; then
+        echo "error: latex failed to translate $name.tex to $name.dvi"
+        exit 1
+    fi
+
+    $DVIPS -o $name.eps $name.dvi
+
+    if [ ! -e "$name.eps" ] ; then
+        echo "error: dvips failed to translate $name.dvi to $name.eps"
+        exit 1
+    fi
 fi
 
 $GHOSTSCRIPT -sDEVICE=$out -r${opt_d} -sOutputFile=$name.$out $name.eps 2> /dev/null
 
 if [ ! -e "$name.$out" ] ; then
-	echo "error: ghostscript failed to translate $name.eps to $name.$out"
-	exit 1
+    echo "error: ghostscript failed to translate $name.eps to $name.$out"
+    exit 1
 fi
 
 # $inline is for images of equations that include an extra dot on the baseline
@@ -154,20 +154,20 @@ fi
 #    in $name.tmp.png is removed to create the final image $name.png
 # 
 if [ $inline -eq 1 ] ; then
-	rm -f $name.pbm $name.tmp.$out
-	
-	$PNMCROP $name.$out > $name.tmp.$out
+    rm -f $name.pbm $name.tmp.$out
 
-	$PNMCUT -width 1 $name.tmp.$out | $PPMTOPGM | $PGMTOPBM > $name.pbm
+    $PNMCROP $name.$out > $name.tmp.$out
 
-#	offset=`expr ${opt_d} / 72 + 2`
-	$PNMCUT -left $opt_o $name.tmp.$out | $PNMCROP | $PNMTOPNG > $name.png
-	
-	if [ $opt_k -eq 0 ] ; then
-		rm -f $name.tmp.$out
-	fi
+    $PNMCUT -width 1 $name.tmp.$out | $PPMTOPGM | $PGMTOPBM > $name.pbm
+
+#   offset=`expr ${opt_d} / 72 + 2`
+    $PNMCUT -left $opt_o $name.tmp.$out | $PNMCROP | $PNMTOPNG > $name.png
+
+    if [ $opt_k -eq 0 ] ; then
+        rm -f $name.tmp.$out
+    fi
 else
-	$PNMCROP $name.$out | $PNMTOPNG > $name.png
+    $PNMCROP $name.$out | $PNMTOPNG > $name.png
 fi
 
 if [ ! -e "$name.png" ] ; then
@@ -179,12 +179,12 @@ if [ $opt_k -eq 0 ] ; then
 
     rm -f $name.dvi $name.aux $name.log
 
-	if [ $ext != "eps" ] ; then
-		rm -f $name.eps
-	fi
+    if [ $ext != "eps" ] ; then
+        rm -f $name.eps
+    fi
 
-	if [ $inline -eq 0 -o $out != "pbm" ] ; then
-    		rm -f $name.$out
+    if [ $inline -eq 0 -o $out != "pbm" ] ; then
+            rm -f $name.$out
     fi
 fi
 
